require('dotenv').config();

var fs = require('fs');
var bodyParser = require('body-parser');
var cloudinary = require('cloudinary').v2;
var formidable = require('formidable');
var express = require('express');



var app = new express();

app.use(bodyParser.urlencoded({ extended: true, type: "application/x-www-form-urlencoded" }));

app.use(bodyParser.json());

app.get("/", (req,res)=> {

 


})


app.post("/uploadImg", (req, res)=> {
    //debugger;
    var form = new formidable.IncomingForm();
    form.parse(req, function(err, fields, files) {
        cloudinary.uploader.upload(files.file.path, { tags: 'basic_sample' }, function (err, image) {
            //console.log();
            console.log("** File Upload");
            if (err) { console.warn(err); }
            console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
            debugger;
            res.send("Image uplaoded");
          });    
    })
   // console.log(req.body)
  

});
var PORT = process.env.PORT;


app.listen(PORT, (req,res)=>{

    console.log("Application started at" + PORT  );
})
